# Generated by Django 2.0.7 on 2018-09-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180919_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='nick name', max_length=128),
        ),
    ]
